### ISSUE TITLE
versionName and versionCode in manifest

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-addressing#12]
https://github.com/w3c/miniapp-addressing/blob/main/docs/Q&A.md#1-what-is-the-relationship-between-version-in-uri-and-versionname--versioncode-in-manifest-by-hax

`versionName` and `versionCode` in manifest were renamed. We should update it in the Q&A document.

**Comment by Sharonzd** [comment]
fixed it in https://github.com/w3c/miniapp-addressing/pull/13

**Comment by xfq** [comment]
Thank you!
