### ISSUE TITLE
Update the explainer

### ISSUE THREAD

**Issue by xfq** [w3c/miniapp-addressing#9]
We need to update the explainer to be consistent with the current (post #4) spec before re-requesting TAG review.

**Comment by Sharonzd** [comment]
Thank you for your reminder! I will update it before the next WG

**Comment by Sharonzd** [comment]
Here is pull request https://github.com/w3c/miniapp-addressing/pull/11

**Comment by xfq** [comment]
Although I have merged #11, I think it should include examples using the https scheme. Would you please add some more examples?

**Comment by Sharonzd** [comment]
Agree with you. See https://github.com/w3c/miniapp-addressing/pull/13.
But I am not sure something about https://github.com/w3c/miniapp-addressing/pull/13/files#diff-2f229b0b8897a11c9577dd7bdccd576d273a2f91700d1bac213ea26f4ff4f082R151
I think the host and origin is inappropriate(either different from normal https url, or different from custom-scheme url),
I need some time to think about it

**Comment by Sharonzd** [comment]
I updated https://github.com/w3c/miniapp-addressing/pull/13 
Changes：
1. Removed "@example.com" in spec examples. because it will cause confusion. So the previously mentioned issue is no longer an issue.
2. Removed outdated Q&A
3. Update explainer

Please review to see if it can be merged.
